class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start1'
        self.MirrorCommand = 'mirror1'
        self.UnzipMirrorCommand = 'unzipmirror1'
        self.TarMirrorCommand = 'tarmirror1'
        self.ZipMirrorCommand = 'zipmirror1'
        self.CancelMirror = 'cancel1'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'list1'
        self.StatusCommand = 'status1'
        self.AuthorizedUsersCommand = 'users1'
        self.AuthorizeCommand = 'authorize1'
        self.UnAuthorizeCommand = 'unauthorize1'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help1'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'clone1'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch1'
        self.TarWatchCommand = 'tarwatch1'
        self.DeleteCommand = 'del'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
